name: Ahk2Exe

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Ahk2Exe (64bit)
      uses: tamo/action-Ahk2Exe@main
      with:
        base: AutoHotkey64.exe
        src: LidAction.ahk

    - run: ls LidAction.exe

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: LidAction.exe
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
