name: Ahk2Exe

on: [push]

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Ahk2Exe (64bit) (default)
      uses: tamo/action-Ahk2Exe@main
      with:
        base: AutoHotkey64.exe
        src: LidAction.ahk

    - run: ls LidAction.exe

    - name: Configure ja-hover
      run: |
        rm LidActionCfg.ahk
        mv LidActionCfg-ja-hover.ahk LidActionCfg.ahk

    - name: Ahk2Exe (64bit) (ja) (hover)
      uses: tamo/action-Ahk2Exe@main
      with:
        base: AutoHotkey64.exe
        src: LidAction.ahk
        opt: /out LidAction-ja-hover.exe

    - run: ls LidAction-ja-hover.exe

    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: LidAction-artifact
        path: |
          LidAction.exe
          LidAction-ja-hover.exe

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          LidAction.exe
          LidAction-ja-hover.exe
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
